### PR TITLE
Fix timestamp reading issue

### LINKED ISSUE #63: Result set cannot read timestamps
Database:
```
sqlite> .schema
CREATE TABLE IF NOT EXISTS "things"(id bigserial primary key, created_at text);
sqlite> select * from things;
1|2020-11-14 21:56:52
```
Code:
```crystal
require "sqlite3"

DB.open("sqlite3:./test.db") do |db|
  db.query "select * from things" do |rs|
    rs.each do
      puts "#{rs.read(Int64)}, #{rs.read(Time)}"
    end
  end
end
```
Output:
```
Unhandled exception: Unexpected char: '\u{0}' at 19: "2020-11-14 21:56:52>>" (Time::Format::Error)
  from ../../../../usr/lib/crystal/time/format/parser.cr:558:11 in 'raise'
  from ../../../../usr/lib/crystal/time/format/parser.cr:554:5 in 'raise'
  from ../../../../usr/lib/crystal/time/format/parser.cr:474:9 in 'char'
  from ../../../../usr/lib/crystal/time/format/pattern.cr:165:9 in 'check_char'
  from ../../../../usr/lib/crystal/time/format/pattern.cr:8:18 in 'visit'
  from ../../../../usr/lib/crystal/time/format.cr:83:5 in 'parse'
  from ../../../../usr/lib/crystal/time/format.cr:81:3 in 'parse'
  from ../../../../usr/lib/crystal/time.cr:1181:5 in 'parse'
  from lib/sqlite3/src/sqlite3/result_set.cr:67:5 in 'read'
  from test.cr:6:34 in '__crystal_main'
  from ../../../../usr/lib/crystal/crystal/main.cr:105:5 in 'main_user_code'
  from ../../../../usr/lib/crystal/crystal/main.cr:91:7 in 'main'
  from ../../../../usr/lib/crystal/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```
However, this is the timestamp format used by SQLite's `current_timestamp`, so not being able to parse it is a problem. I'm not sure if the appropriate solution is a change here or somewhere else, but I'm posting it here as a starting point.

Occurs on master branch.

### PR DESCRIPTION
**Pull request by tenebrousedge**
Also adds a couple of basic tests for ResultSet
Should fix #63

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by yujiri8** [comment]
Thanks! Fixing this would be epic.

**Review by bcardiff — CHANGES_REQUESTED** [review]
This PR is not right as it is.

* Although Time instances are stored with millisecond information, that part is not returned. Yet no spec checks that currently.

You can add to db_spec.cr the following. Before this PR it passes, after this PR it fails.

```crystal
sample_value Time.utc(2016, 2, 15, 10, 15, 30, nanosecond: 123000000), "text", "'2016-02-15 
10:15:30.123'", type_safe_value: false
```

* Performing a String concatenation in the bind_arg should be avoided. Otherwise there will be an extra unneeded allocation each time that is used.

I think this should be implemented by allowing a fallback of date formats in `ResultSet#read(Time.class)`/`ResultSet#read(Time?.class)`

**Comment by tenebrousedge** [comment]
I might be confused about what you mean there @bcardiff . This code should have a fallback for the default behavior of SQLite? The default path should be to throw an error and recover?

**Comment by bcardiff** [comment]
When reading values as Time, if the format matches `"%F %H:%M:%S.%L"` then milliseconds should be used. If there is no millisecond information trying to parse a time with `"%F %H:%M:%S"` is good. I don't think `Time.parse` allows optional `.%L` so I think we should check for a `.` char and parse using either pattern based on that.

In the current state this PR stores milliseconds but they are not read.

**Comment by tenebrousedge** [comment]
Yes, it stores milliseconds but they are not read because, as far as I have been able to determine, this is the default behavior of SQLite. If this is not the case, or if there is some trivial configuration change that would result in SQLite returning milliseconds, then I would agree that checking for `.` makes sense.

**Comment by bcardiff** [comment]
You can use time with milliseconds in sqlite: `select STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW');`

In fact there are multiple valid time formats: https://sqlite.org/lang_datefunc.html#time_strings.

So iin other words what I am saying is that we should add support for `YYYY-MM-DD HH:MM:SS` without dropping
`YYYY-MM-DD HH:MM:SS.SSS`. And use the later as default format to store information.

**Comment by yujiri8** [comment]
@tenebrousedge are you coming back to this or should I try?

**Comment by yujiri8** [comment]
Issue has now been fixed by #68.

**Pull request closed without merging**
